services:
  php:
   build:
    context: .
    dockerfile: Dockerfile
   container_name: "${php_server}"
   volumes:
    - .:/app
   networks:
    - app-network
   depends_on:
    - db

  nginx:
    image: nginx:alpine
    container_name: "${nginx_server}"
    volumes:
    - ./:/app
    - ./nginx-conf:/etc/nginx/conf.d/
    ports:
    - 8080:80
    networks:
    - app-network
  db:
   image: mysql:5.7
   container_name: db-container
   environment:
     MYSQL_DATABASE: "${DB_DATABASE}"
     MYSQL_USER: "${DB_USERNAME}"
     MYSQL_PASSWORD: "${DB_PASSWORD}"
     MYSQL_ROOT_PASSWORD: DEMO@123456
   ports:
   - 3306:3306
   networks:
   - app-network

networks:
  app-network:
    driver: bridge
