version: '3.9'
services:
  nginx-service:
     image: nginx:latest
     container_name: nginx-container
     volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      - "./codefiles:/var/www/html/"
     ports:
      - "80:80"
     networks:
      - web-network

  php-service:
     build:  
      context: .
      dockerfile: ./php/Dockerfile
     container_name: php-container
     volumes:
      - "./codefiles:/var/www/html"
     networks:
      - web-network

networks:
  web-network:
    driver: bridge     
