name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: self-hosted 

    steps:
 
    - uses: actions/checkout@v3
    - name: Copy .env
    - run: touch  test.php


